### ISSUE TITLE
ATE and RTE calculation

### ISSUE THREAD

**Issue by TiloccaS** [nesl/agrobot#2]
Hello these days I had the pleasure of using your repository, I wanted to ask if the metrics defined in the Cal_TE function are the same from which you obtain the values in the reference paper, also I wanted to ask you how they were defined in the code.

Thank you

**Comment by swapnilsayansaha** [comment]
Absolute trajectory error and relative trajectory error are defined in https://ieeexplore.ieee.org/document/9196860/similar and also another paper of ours: https://dl.acm.org/doi/abs/10.1145/3534594 

Ate is the displacement error over the whole trajectory while rte is the ate for 1 minute.
